services:
  mongo:
    image: mongo:7.0.5
    restart: always
    container_name: mongo_7_0_5
    # command: --serviceExecutor adaptive
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/etc/mongo
      - mongo_data:/data/db
      
  mongo-express:
    image: mongo-express:1.0.2-20
    container_name: mongo_express_1_0_2_20
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
      ME_CONFIG_MONGODB_SERVER: mongo_7_0_5

volumes:
  mongo_data: {}