# Generated by Django 4.1.13 on 2024-03-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.FloatField()),
            ],
        ),
    ]
